/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package team;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Michael
 */
public class FlowTeamGUI extends javax.swing.JFrame {

    /**
     * Creates new form FlowTeamLoFi
     */
    Control control;
    DefaultListModel<Person> persons, members;
    DefaultListModel<Team> teams;
    public FlowTeamGUI() {
        initComponents();
        control = new Control();
        persons = new DefaultListModel();
        teams = new DefaultListModel();
        members = new DefaultListModel();
        jListPersons.setModel(persons);
        jListPersonsManageTeams.setModel(persons);
        jListTeams.setModel(teams);
        jListTeamsManageTeams.setModel(teams);
        jListTeamMembers.setModel(members);
        for(int i =0; i<control.getPersonList().size(); i++){
            persons.add(i, control.getPerson(i));
        }
        for(int i =0; i<control.getTeamList().size(); i++){
            teams.add(i, control.getTeam(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPersons = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNewPersonName = new javax.swing.JTextField();
        jTextFieldNewPersonAdmin = new javax.swing.JTextField();
        jTextFieldNewPersonAnalyst = new javax.swing.JTextField();
        jTextFieldNewPersonCreative = new javax.swing.JTextField();
        jTextFieldNewPersonFinisher = new javax.swing.JTextField();
        jButtonNewPerson = new javax.swing.JButton();
        jButtonRemovePerson = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTeams = new javax.swing.JList();
        jButtonShowTeam = new javax.swing.JButton();
        jLabelShowTeamLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaShowTeamArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListTeamsManageTeams = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListPersonsManageTeams = new javax.swing.JList();
        jButtonCreateTeam = new javax.swing.JButton();
        jButtonSaveTeam = new javax.swing.JButton();
        jButtonDeleteTeam = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListTeamMembers = new javax.swing.JList();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaTeamInfo = new javax.swing.JTextArea();
        jButtonAddPersonManage = new javax.swing.JButton();
        jButtonRemovePersonManage = new javax.swing.JButton();
        jButtonShowManageTeams = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Persons");

        jListPersons.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListPersons);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Add Person");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Characteristics");

        jLabel5.setText("Administrator");

        jLabel6.setText("Analyst");

        jLabel7.setText("Creative");

        jLabel8.setText("Finisher");

        jTextFieldNewPersonName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldNewPersonAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNewPersonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNewPersonAdminActionPerformed(evt);
            }
        });

        jTextFieldNewPersonAnalyst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldNewPersonCreative.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldNewPersonFinisher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonNewPerson.setText("< Add");
        jButtonNewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewPersonActionPerformed(evt);
            }
        });

        jButtonRemovePerson.setText("Remove");
        jButtonRemovePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemovePersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonRemovePerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNewPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(133, 133, 133)
                        .addComponent(jTextFieldNewPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldNewPersonFinisher, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNewPersonCreative, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNewPersonAnalyst, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNewPersonAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNewPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNewPerson)
                                .addGap(54, 54, 54)
                                .addComponent(jButtonRemovePerson))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldNewPersonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldNewPersonAnalyst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextFieldNewPersonCreative, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextFieldNewPersonFinisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Persons", jPanel1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Teams");

        jListTeams.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListTeams);

        jButtonShowTeam.setText("Show");
        jButtonShowTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowTeamActionPerformed(evt);
            }
        });

        jLabelShowTeamLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelShowTeamLabel.setText("Team X");

        jTextAreaShowTeamArea.setColumns(20);
        jTextAreaShowTeamArea.setLineWrap(true);
        jTextAreaShowTeamArea.setRows(5);
        jTextAreaShowTeamArea.setText("Members:\nHans\t10, 10,  4,  6\nGrethe\t 6,  4, 12,  8\nTim\t 4, 12,  6,  8\nBente\t 8,  6,  9,  7\n\nTotal\t28, 32, 31, 29\n\nTeam Info:\nWorking on something\nStarted on that date\nDeadline for prototype\netc. ");
        jScrollPane3.setViewportView(jTextAreaShowTeamArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonShowTeam)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelShowTeamLabel)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelShowTeamLabel)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3)
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jButtonShowTeam)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Teams", jPanel2);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Teams");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Members");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Persons");

        jListTeamsManageTeams.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListTeamsManageTeams.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTeamsManageTeamsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jListTeamsManageTeams);

        jListPersonsManageTeams.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jListPersonsManageTeams);

        jButtonCreateTeam.setText("Create Team");
        jButtonCreateTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateTeamActionPerformed(evt);
            }
        });

        jButtonSaveTeam.setText("Save Team");
        jButtonSaveTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveTeamActionPerformed(evt);
            }
        });

        jButtonDeleteTeam.setText("Delete Team");
        jButtonDeleteTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteTeamActionPerformed(evt);
            }
        });

        jListTeamMembers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jListTeamMembers);

        jLabel14.setText("Total:");

        jLabel15.setText("30");

        jLabel16.setText("30");

        jLabel17.setText("30");

        jLabel18.setText("30");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Team Info");

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextAreaTeamInfo.setColumns(20);
        jTextAreaTeamInfo.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaTeamInfo.setLineWrap(true);
        jTextAreaTeamInfo.setRows(5);
        jTextAreaTeamInfo.setText("This is where\nyou edit the\ninformation\nabout the team");
        jScrollPane7.setViewportView(jTextAreaTeamInfo);

        jButtonAddPersonManage.setText("<");
        jButtonAddPersonManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPersonManageActionPerformed(evt);
            }
        });

        jButtonRemovePersonManage.setText(">");
        jButtonRemovePersonManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemovePersonManageActionPerformed(evt);
            }
        });

        jButtonShowManageTeams.setText("Show");
        jButtonShowManageTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowManageTeamsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonShowManageTeams))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButtonCreateTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel19))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButtonDeleteTeam))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonSaveTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAddPersonManage, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonRemovePersonManage, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jButtonShowManageTeams))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButtonAddPersonManage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRemovePersonManage)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDeleteTeam))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCreateTeam, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jButtonSaveTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manage Teams", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNewPersonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNewPersonAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNewPersonAdminActionPerformed

    private void jButtonNewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewPersonActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldNewPersonName.getText();
        int admin, analyst, creative, finisher;
        admin = Integer.parseInt(jTextFieldNewPersonAdmin.getText());
        analyst = Integer.parseInt(jTextFieldNewPersonAnalyst.getText());
        creative = Integer.parseInt(jTextFieldNewPersonCreative.getText());
        finisher = Integer.parseInt(jTextFieldNewPersonFinisher.getText());
        Person p = new Person(name, admin, analyst, creative, finisher);
        control.addPerson(p);
        persons.removeAllElements();
        for(int i =0; i<control.getPersonList().size(); i++){
            persons.add(i, control.getPerson(i));
        }
    }//GEN-LAST:event_jButtonNewPersonActionPerformed

    private void jButtonRemovePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovePersonActionPerformed
        // TODO add your handling code here:
        int selected = jListPersons.getAnchorSelectionIndex();
        control.removePerson(selected);
        persons.remove(selected);
        
    }//GEN-LAST:event_jButtonRemovePersonActionPerformed

    private void jButtonShowTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowTeamActionPerformed
        // TODO add your handling code here:
        int selected = jListTeams.getAnchorSelectionIndex();
        String str = "Members:\n"+control.getTeam(selected);
    }//GEN-LAST:event_jButtonShowTeamActionPerformed

    private void jButtonCreateTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateTeamActionPerformed
        // TODO add your handling code here:
        String name = JOptionPane.showInputDialog(null, "What is the teams' name?");
        control.createTeam(name);
        teams.removeAllElements();
        for(int i =0; i<control.getTeamList().size(); i++){
            teams.add(i, control.getTeam(i));
        }
    }//GEN-LAST:event_jButtonCreateTeamActionPerformed

    private void jButtonDeleteTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteTeamActionPerformed
        // TODO add your handling code here:
        int selected = jListTeamsManageTeams.getAnchorSelectionIndex();
        control.removeTeam(selected);
        teams.remove(selected);
    }//GEN-LAST:event_jButtonDeleteTeamActionPerformed

    private void jListTeamsManageTeamsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTeamsManageTeamsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jListTeamsManageTeamsMouseClicked

    private void jButtonAddPersonManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPersonManageActionPerformed
        // TODO add your handling code here:
        int selected = jListPersonsManageTeams.getAnchorSelectionIndex();
        members.addElement(control.getPerson(selected));
        control.getPersonList().remove(selected);
        persons.remove(selected);
        jListTeamMembers.setModel(members);
        jListPersonsManageTeams.setModel(persons);
    }//GEN-LAST:event_jButtonAddPersonManageActionPerformed

    private void jButtonShowManageTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowManageTeamsActionPerformed
        // TODO add your handling code here:
        int selected = jListTeamsManageTeams.getAnchorSelectionIndex();
        for(int i=0;i<control.getTeam(selected).getTeam().size();i++){
            Person p = new Person(control.getTeam(selected).getPerson(i).toNoSpaceString());
            members.addElement(p);
        }
        jListTeamMembers.setModel(members);
    }//GEN-LAST:event_jButtonShowManageTeamsActionPerformed

    private void jButtonRemovePersonManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovePersonManageActionPerformed
        // TODO add your handling code here:
        int selected = jListTeamMembers.getAnchorSelectionIndex();
        control.addPerson(members.get(selected));
        persons.addElement(members.getElementAt(selected));
        members.remove(selected);
        jListTeamMembers.setModel(members);
        jListPersonsManageTeams.setModel(persons);
    }//GEN-LAST:event_jButtonRemovePersonManageActionPerformed

    private void jButtonSaveTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveTeamActionPerformed
        // TODO add your handling code here:
        int selectedTeam = jListTeamsManageTeams.getAnchorSelectionIndex();
        for(int i=0;i<members.getSize();i++){
            control.getTeam(selectedTeam).addPerson(members.get(i));
        }
        System.out.println(control.getTeam(selectedTeam));
    }//GEN-LAST:event_jButtonSaveTeamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlowTeamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlowTeamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlowTeamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlowTeamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FlowTeamGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPersonManage;
    private javax.swing.JButton jButtonCreateTeam;
    private javax.swing.JButton jButtonDeleteTeam;
    private javax.swing.JButton jButtonNewPerson;
    private javax.swing.JButton jButtonRemovePerson;
    private javax.swing.JButton jButtonRemovePersonManage;
    private javax.swing.JButton jButtonSaveTeam;
    private javax.swing.JButton jButtonShowManageTeams;
    private javax.swing.JButton jButtonShowTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelShowTeamLabel;
    private javax.swing.JList jListPersons;
    private javax.swing.JList jListPersonsManageTeams;
    private javax.swing.JList jListTeamMembers;
    private javax.swing.JList jListTeams;
    private javax.swing.JList jListTeamsManageTeams;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaShowTeamArea;
    private javax.swing.JTextArea jTextAreaTeamInfo;
    private javax.swing.JTextField jTextFieldNewPersonAdmin;
    private javax.swing.JTextField jTextFieldNewPersonAnalyst;
    private javax.swing.JTextField jTextFieldNewPersonCreative;
    private javax.swing.JTextField jTextFieldNewPersonFinisher;
    private javax.swing.JTextField jTextFieldNewPersonName;
    // End of variables declaration//GEN-END:variables
}
